### ISSUE TITLE
android pie开启全屏手势返回键失效

### ISSUE THREAD

**Issue by xinyu3ru** [fg607/RelaxFinger#1]
android pie开启全屏手势返回键失效。
设置的单次点击返回，开启全屏手势之后，失效。只能用手势返回。

**Comment by fg607** [comment]
@xinyu3ru 其他功能呢？多任务手势是不是也失效了？用的第三方全屏手势APP？

**Comment by xinyu3ru** [comment]
其他功能暂时没有发现有影响，一加6手机，自带的手势。能拖出快速启动软件的界面，没有影响。

**Comment by xinyu3ru** [comment]
还有返回home界面的双击也失效了

**Comment by fg607** [comment]
@xinyu3ru 重启下试试，不行就没办法了，可能是系统在全面屏手势的时候把辅助功能部分接口停用了
